Summary:	The Autoconf Macro Archive
Name:		autoconf-archive
Version:	2012.09.08
Release:	1
License:	GPL v3+ with exceptions
Group:		Development/Tools
Source0:	http://ftp.gnu.org/gnu/autoconf-archive/%{name}-%{version}.tar.xz
# Source0-md5:	670ca8a5d2d85437f034f0448ee9470d
URL:		http://www.gnu.org/software/autoconf-archive/
BuildRequires:	tar >= 1:1.22
BuildRequires:	xz
Requires:	autoconf
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
The GNU Autoconf Archive is a collection of more than 450 macros for
GNU Autoconf that have been contributed as free software by friendly
supporters of the cause from all over the Internet.

%prep
%setup -q

%build
%configure
%{__make}

%install
rm -rf $RPM_BUILD_ROOT
%{__make} install \
	INSTALL="install -p" \
	DESTDIR=$RPM_BUILD_ROOT

# remove dir file which will be generated by /sbin/install-info
rm -f $RPM_BUILD_ROOT%{_infodir}/dir
# document files are installed another location
rm -r $RPM_BUILD_ROOT%{_datadir}/%{name}

%clean
rm -rf $RPM_BUILD_ROOT

%post	-p /sbin/postshell
-/usr/sbin/fix-info-dir -c %{_infodir}

%postun	-p /sbin/postshell
-/usr/sbin/fix-info-dir -c %{_infodir}

%files
%defattr(644,root,root,755)
%doc AUTHORS COPYING* ChangeLog NEWS README TODO
%{_aclocaldir}/*.m4
%{_infodir}/autoconf-archive.info*
